spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: liquibase/master.xml
    enabled: true